### ISSUE TITLE
[FEAT] 추천시스템 모델개발

### ISSUE THREAD

**Issue by Jinlee057** [our-ml-flow/nft_recsys#3]
## Background
- 데이터 파이프라인을 통해 저장된 데이터를 이용, 유저 기반의 NFT Collection 추천 모델을 개발합니다.

## Todo
- [ ] DB서버에서 데이터 가져오기
       Surprise 라이브러리 사용 예정이기 때문에 데이터는 (user, collection, 평점) 형식으로 가져옵니다.
- [ ] 추천 알고리즘 개발
       Surprise 라이브러리 제공 알고리즘 이용하여 각 알고리즘 평가 진행 합니다.
- [ ] 최종 선정된 모델 이용 파이프라인 구성
